### ISSUE TITLE
Brain Dump

### ISSUE THREAD

**Issue by nelsonic** [dwyl/product-roadmap#12]
The "workflow" of the @dwyl app will be: 
1. ***Capture***
2. ***Categorise***
3. ***Complete***

The _first_ step in our app is to help the person ***capture*** everything on their mind.
We call this step/feature the "**brain dump**". The purpose is to **empty** your **_working_ memory** so that you're not thinking about too many things and can **focus** on the **_one_ most important thing**. "_Free your mind_" ...

![free your mind matrix](https://media1.tenor.com/images/dfcc80661027619198b2d9a6d8706f44/tenor.gif "Free Your Mind Neo")

> If you haven't seen [The Matrix](https://www.imdb.com/title/tt0133093) this reference will be lost ... Seriously, watch it!

![brain-dump-before-after](https://user-images.githubusercontent.com/194400/68108635-3497be00-fee0-11e9-83f0-6a56ecc99623.jpg)

+ https://hustletostartup.com/brain-dumping (_post needs some editing_)
+ https://anniemueller.com/brain-dump-noun-1/ (_definition and intro image_)

# Todo / Acceptance Criteria

+ [ ] A `textarea` for free text input 
  + [ ] Informative / action-inducing placeholder text 
  (_tbd ... for now "write down everything that is on your mind" ... we will A/B test this later!_)
  + [ ] Automatically expands to use the available space on mobile device
+ [ ] Text is saved to Phoenix backend and stored in **`text`** field in Postgres

For now this is "enough" to get started.
We don't need anything fancy it just needs to work.

**Comment by iteles** [comment]
My prediction is that people will want to add tags _as_ they brain dump for _some_ form of categorisation but that's definitely a next step 👍

**Comment by nelsonic** [comment]
@iteles agreed. We cannot expect to impose a strict separation of the steps. 
in many cases people will capture, complete and _then_ categorise their tasks. 

Our job as UX designers / developers is to make the process seamless in any order.
