### ISSUE TITLE
New Persona: Busy Working Mother

### ISSUE THREAD

**Issue by nelsonic** [dwyl/product-roadmap#30]
https://www.bbc.com/worklife/article/20210518-the-hidden-load-how-thinking-of-everything-holds-mums-back

### "_When it comes to household responsibilities, women perform far more cognitive and emotional labour than men. Why is this, and is there anything we can do about it?_"

![image](https://user-images.githubusercontent.com/194400/143594125-bb5e7429-6ed4-4a2b-8e8e-de78e08c1b0e.png)

> Also, notice the [Facebook](https://github.com/dwyl/learn-react/issues/23#issuecomment-647521076) **banner ad** ... why does Facebook need to advertise? 🤷‍♂️ 

# Todo

+ [x] Create persona using https://github.com/dwyl/process-handbook/tree/master/personas
+ [x] Create a high resolution screenshot of the resulting persona
+ [x] ***Print*** the persona for the wall in the office @home to serve as a reminder.

**Comment by nelsonic** [comment]
@seaneady this could be a good exercise for you in your Product Owner / UX Research journey. https://github.com/dwyl/hq/issues/577 💭 
If you want to _pair_ on it at some point, I can speed run it with you, 🧑‍💻 
record my screen on Zoom, upload the video and you can do the _next_ one solo. 📺

**Comment by nelsonic** [comment]
Obvs the irony of @iteles, a busy working mum of "Two Under Two!" having this assigned to her is not lost on any of us. 😞 
Inês is literally the person who would _immediately_ benefit from our `App` if it was already working as needed. 💭

**Comment by seaneady** [comment]
I'd definitely like to take a shot at this. Happy with your suggestion above for the first iteration, thanks!
@iteles will definitely serve as valued inspiration and I'd be happy to take this off her hands.

**Comment by nelsonic** [comment]
Let's take a look at this tomorrow morning after standup. 👌

**Comment by nelsonic** [comment]
@seaneady please upload a screenshot of the work you did in Google Docs. 🙏 📷 
Note: http://www.take-a-screenshot.org/ (all platforms)

**Comment by seaneady** [comment]
<img width="976" alt="Screenshot 2023-01-25 at 11 53 22 AM" src="https://user-images.githubusercontent.com/122034315/214532555-b3bcad09-f552-40ce-a5c8-e82ec2906d4f.png">

**Comment by nelsonic** [comment]
Epic @seaneady! 🎉

**Comment by nelsonic** [comment]
Can you please copy-paste the  avatar image so that we have it in full resolution for printing? 🙏

**Comment by seaneady** [comment]
<img width="359" alt="Screenshot 2023-01-25 at 11 57 32 AM" src="https://user-images.githubusercontent.com/122034315/214533504-329afd0c-faf4-4f30-b9ca-ab50d9ade9b2.png">

**Comment by seaneady** [comment]
Let me know if that's ok?

**Comment by nelsonic** [comment]
Based on @seaneady's fine work:
<img width="1472" alt="image" src="https://user-images.githubusercontent.com/194400/214534492-7252fe45-79f2-4c52-8ab1-2c64d2ba44f2.png">

PR: https://github.com/dwyl/process-handbook/pull/158

**Comment by nelsonic** [comment]
Minor adjustments: 

<img width="1479" alt="image" src="https://user-images.githubusercontent.com/194400/214536370-5b5cc908-8e83-40f8-ab5d-5f02159517da.png">

PR is ready for review: https://github.com/dwyl/process-handbook/pull/158#issuecomment-1403375031

**Comment by nelsonic** [comment]
Tidy screenshot: (the trailing 3 on the next line was bugging me...)
<img width="1504" alt="image" src="https://user-images.githubusercontent.com/194400/214538321-b80e762e-e6f7-4507-bf52-b52500d8d874.png">

**Comment by nelsonic** [comment]
Also Updated my _own_ persona while I had it open:
<img width="1536" alt="image" src="https://user-images.githubusercontent.com/194400/214541196-0580e31c-579e-46e3-be44-24611859750c.png">

**Comment by nelsonic** [comment]
Ironically our "busy working mum of 2" is too busy with her work to look at this. 
Closing. ✅

**Comment by iteles** [comment]
Your ' busy working mother of two' has been on maternity leave and only looking at priority 1 issues 😅

I would just add to the pain points: no way to understand which of her tasks are the highest value or are critical. 

And might suggest using a more universally understood name?

Looking great though. Short and sweet. Like the format you guys ended up with too.
