### ISSUE TITLE
Time-tracking MVP

### ISSUE THREAD

**Issue by nelsonic** [dwyl/product-roadmap#31]
We need a way of keeping track of who is working on what for our project. 
This will become a core feature of our **product**. 
It's there on the MVP feature roadmap: https://github.com/dwyl/product-roadmap#mvp-basic-workflow

![todo-list-with-timer png](https://user-images.githubusercontent.com/194400/173045592-c82159f2-909f-427a-ac39-7e33892d03e7.svg)

Essentially we are building a Todo List with a Stop Watch. ✅ +⏳  
Hence the reason for us writing tutorials for these _individual_ components ... 💭 
+ [x] https://github.com/dwyl/javascript-todo-list-tutorial
+ [x] https://github.com/dwyl/stopwatch

Once you click/tap on **`Start`** it will insert a **`timer`** record associated with the **`item`** 
see schema: https://github.com/dwyl/app-mvp-phoenix#create-schemas

> **Note**: this "fits in" to our bigger picture road map: once you have [***`captured`***](https://github.com/dwyl/product-roadmap/blob/master/capture.md) and [***`categorized`***](https://github.com/dwyl/product-roadmap#why-are-we-building-an-app) your thoughts (**`items`**), _some_ of them will become **`tasks`**. 
When you are ***`completing`*** those **`tasks`**, you need to keep track of how much time you have spent on them. That's where Time-tracking comes in! Knowing how long something has taken is _essential_!
So in essence we are "building the bridge from both ends". The time-tracking aspect is 100% part of _completing_ a task. We can build that part of it _without_ having a fancy editor. 

+ [x] Capture: we want to build a _beautiful_ and responsive "capture" interface that has markdown (and eventually Rich Text) support e.g. images, annotations etc. but we have to start with **`plaintext`** first.
  We have a sub-task to build the "capture" part in our **`gitea-demo`** (_tutorial_): 
  + [ ] Real-time Collaborative Markdown Editor with **`LiveView`**: https://github.com/dwyl/gitea-demo/issues/12
+ [x] Tech Stack? 
  + [x] Thinking of using **`PETAL`** https://github.com/dwyl/technology-stack/issues/87 for this MVP because **`Tailwind`** looks a lot easier to build Mobile-first Apps with (than **`Tachyons`** where it's still totally possible, but more difficult..._) and from listening to the 
 There is a checklist in that issue we need to try and complete as quickly as possible.<sup>1</sup>
+ [x] Exclusively Web-based and online-only. (will not work offline because `LiveView` ... 🙄 but that's "OK" for MVP!)

## Features

+ [x] **`Auth`** using https://auth.dwyl.com 🔒 
+ [x] **Basic** ***`capture`*** task to be done as **`plaintext`**. 📝 
+ [x] **`Start`** timer for the task ⏳ 
+ [x] **`Stop`** timer ✅ 

<sup>1</sup>We don't have to have ***complete*** tutorials for everything, but we need to capture the basics so that both we (our current core team) and other people can find our "learn-..." tutorial/notes _useful_. But our main objective is learning the tech/tools _ourselves_ as quickly as possible so that we can build our MVP!

@SimonLab let me know if this is clear or if I can clarify anything ... 🙏

**Comment by nelsonic** [comment]
This functionality is now fully covered in the MVP: https://github.com/dwyl/app-mvp-phoenix/issues/89#issuecomment-1190752035 🎉 
@SimonLab please test: [mvp.fly.dev](https://mvp.fly.dev/) and provide feedback. 👍 
(PR https://github.com/dwyl/app-mvp-phoenix/pull/90 will be assigned very shortly... 🧑‍💻 ⏳ )
