### ISSUE TITLE
Chore: Clarify the Problem/Challenge We Are Solving 💭 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/product-roadmap#36]
At present the [What Problem Are We Solving?](https://github.com/dwyl/product-roadmap/tree/c3493258d0355ba2cb04d4ed61052483f49d5f8b#what-problem-are-we-solving) section of the `README.md` has the following:
![image](https://user-images.githubusercontent.com/194400/185372508-9569370f-6302-4449-8ed2-be519469651e.png)

This is unclear. We can fix it.

# Todo

+ [x] Succinctly describe the problem we are trying to solve.
+ [x] Add Table of Contents
+ [x] Review Section headings / nesting
+ [x] Create PR
+ [x] Assign for review

**Comment by nelsonic** [comment]
## "_I **don't have time**_", often means "_It's **not a priority**_" ~ Laura Vanderkam 

"How to gain control of your free time": https://youtu.be/n3kNlFMXslo
[![image](https://user-images.githubusercontent.com/194400/185357475-b6526a85-b2c5-4951-8457-525c8c94949f.png)](https://youtu.be/n3kNlFMXslo)

**Comment by nelsonic** [comment]
PR: https://github.com/dwyl/product-roadmap/pull/38
