### ISSUE TITLE
Deploy `Flutter` App in `iOS AppStore` and `Android PlayStore`

### ISSUE THREAD

**Issue by nelsonic** [dwyl/product-roadmap#48]
Recently spent a few hours on a Train with patchy network and the interface of the MVP didn’t _allow_ me to input a new `item`. The `item.text` input was not focus-able in the `LiveView`. :sad:

<img width="855" alt="mvp unable to input new item.text" src="https://github.com/dwyl/imgup/assets/194400/ba1a37bd-3112-4a65-a23c-acd8c642e244">

and then the page timeout completely: 

<img width="856" alt="mvp timeout without network" src="https://github.com/dwyl/imgup/assets/194400/d3ae6565-920d-4a75-abf1-57072ab9b3f3">

This is totally lame and we need to address it as our collective top priority. The `App` _needs_ to work _offline_. We need to work back from that goal and create our roadmap. 
	

# Todo

+ [ ] Investigate and _document_ deployment to **`iOS` App Store**
+ [x] ~~ITC to release her iPhone 12 Pro for Lucho ***or*** we can~~ order a new `iPhone SE 2022` to use as a Dev device.
+ [ ] Test on _real_ device(s) wherever possible!
+ [ ] Nelson to setup Apple Developer Account, and pay the annual fee!

## `Android`

+ [ ] Investigate and _comprehensively_ document the steps to deploy **`Google Play` Store** (@LuchoTurtle is best for investigating this as he uses `Android` daily.

**Comment by nelsonic** [comment]
@LuchoTurtle once you've had a chance to wrap up your work on `WYSIWYG` both in the `demo` and then in the `App`,
this is our next highest priority. We need a checklist of _everything_ we need in order to deploy the `Flutter App` to the `iOS AppStore` and `Google Play` Store. Then we can work our way through that list. 🙏
