### ISSUE TITLE
Timeline and dependencies

### ISSUE THREAD

**Issue by iteles** [dwyl/product-roadmap#5]
Using Github Projects, I've found that whilst this is a useful feature, the place it is most lacking is in giving a clear view of dependencies and how a  shift in one tasks's start date or length impacts the project as a whole.

The requirements for a simple MVP of this feature would be:

### Requirements
There are a few _key_ features we need if we're going to build this:
+ [ ] Visual date columns
  + Ideally days but week blocks also works if this is easier initially
  + Stick to the top of the page so scrolling is possible
+ Task features:
  + [ ] Create new tasks (Github issues)
  + [ ] Determine length of task
  + [ ] Determine task start date
  + [ ] Import new tasks into app
  + [ ] Assign 'owner' to a task (e.g. Carlos, electricians, etc)
+ [ ] App displays the name and owner of the task (either displayed underneath or on hover or on click to avoid UI issues for now)
+ [ ] Edit task start date quickly and easily as this is the thing in the application which is likely to be changed the most
+ [ ] Make one tasks dependent on the completion of another
  + [ ] When one task start date or length is changed, the other tasks that are dependent on it move accordingly

### Nice to Have's
But we can 'launch' without these:
+ [ ] Create 'tracks' in app (e.g. `Dining room expansion` or `Swimming pool`)
+ [ ] Allow tasks to be displayed one after the other on the same line when they are linked
+ [ ] Colour code by owner
+ [ ] Edit task length within app
