### ISSUE TITLE
Prioritisation & Visualisation | Project management 'holes' left in Github

### ISSUE THREAD

**Issue by iteles** [dwyl/product-roadmap#8]
## Why?

> People overestimate what they can do in one year and _underestimate_ what they can do in **ten** years.

~ Bill Gates

We currently use Github to hold all of our open tasks https://github.com/dwyl/contributing

Whilst this is invaluable for maintaining a [single source of truth](https://github.com/dwyl/github-reference#why) and pays many dividends with respect to our ability to have a mostly up-to-date view of what is happening, it is _by no means a perfect system_.

If we want to ***truly affect change*** and ensure we and everyone around us is able to reach their potential and be effective so that they can **free up time and brainspace for the people and activities they love**, a big part of that is having a system that _keeps you quasi-effortlessly **moving towards your goals**_.

It should work in the background and not take up your brainpower but rather **give you a clear direction and inspire you to action** whenever you look at it.

## What?

Github's biggest flaws from a project management perspective, as far as I can see, are two-fold:
#### 1. Prioritisation
Truly understanding what the next most important task is to be done:  
  + **For developers/those completing the tasks:** We make do with ordering tasks in milestones but this is _cumbersome to keep up to date_ and was often ignored with the habit of clicking into the milestone itself never being fully formed. With the addition of github projects to the workflow, this has become easier - my only complaint here is the lack of a view of 'the big picture'.
  + **For product owners:** Unless there is a disaster in production, it is hardly ever 'obvious' which task is the highest priority. Github projects has helped quite a lot in terms of _communicating_ priorities but there are still some real issues here:
    + Whilst the priority labels are useful, for larger projects we've found that `priority-3` and often `priority-2` become a behemoths and trying to sort through these to adjust priorities is incredibly time consuming
    + It is pretty much impossible to tell when an issue is dependent on another for completion - this happens often and is a huge blindspot for product owners when it comes to prioritisation 
    + Understanding which issues are 'almost done' and the project would benefit from prioritising, especially once they have come back from being tested and have additional comments - no longer relying on an acceptance criteria checklist - is very difficult
    + Whilst Github projects have helped with team communication, it is a real bane to move things around once there are  more than 15 issues in the project and with the visibility of each column being limited to 4-5 issues tops, there is no way to get a good overall feel for the project here
    + Large numbers of issues still create overwhelm and a false sense of "We need everything for our MVP!"

#### 2. Visualisation
I've alluded to this multiple times above but the real difficulty with Github is being able to have a clear, visual representation of where things are at.
+ What are the overall timelines?
+ How do I go about understanding the wider project in a way that will clearly let me prioritise what we need for our MVP vs what we really should be validating with users _before_ we build it out?
+ What has a dependency on something else?
+ If this thing is delayed, what is the true knock-on effect for the whole project?
+ How do I know when the best time to do user testing is?
+ If too many things are expected from me (in whatever my role is) during a certain period of time in order to keep to the project timelines, how do I see that coming down the line and mitigate the risk ahead of the panic?

At dwyl specifically, there are three key places where this lack of prioritisation and importantly the lack of visualisation is slowing us down:
+ Our product roadmap
+ Construction work on https://github.com/dwyl/home
+ Client projects

But this is ***much bigger than dwyl***.

Achieving your goals, planning trips, preparing for life events, making big decisions, knowing what to delegate, making sure your life admin is in order, **all of these can be made much easier and more efficient with system that works _for_** you rather than against you or even just _with_ you.

## How?
My instinct here is that solving visualisation will solve a lot of the prioritisation issues so _visualisation_ is the place to start.

### Tasks
+ [ ] Research existing project visualisation tools (excepting kanban boards, we already have this in Github Projects and it falls short)
+ [ ] Compile list of useful features
+ [ ] Trial existing tools
+ [ ] Review tools in light of required features and determine whether we want to build something ourselves

### Thundercats Hooooooooo!
(for the uninitiated in 80s cartoons: https://youtu.be/mnhrz5nDDa4?t=10)

<img src="https://vignette.wikia.nocookie.net/logocomics/images/b/b0/Thundercats-logo.png/revision/latest?cb=20171129215230" alt="Thundercats logo" height="200">

**Comment by iteles** [comment]
# Spec

There are a few _key_ features we need:
+ [ ] Visual date columns
  + Ideally days but week blocks also works if this is easier initially
  + Stick to the top of the page so scrolling is possible
+ Task features:
  + [ ] Create new tasks 
  + [ ] Determine length of task
  + [ ] Determine task start date
  + [ ] Import new tasks into app
  + [ ] Assign 'owner' to a task 
+ [ ] App displays the name and owner of the task (either displayed underneath or on hover or on click to avoid UI issues for now)
+ [ ] Edit task start date quickly and easily as this is the thing in the application which is likely to be changed the most
+ [ ] Make one tasks dependent on the completion of another
  + [ ] When one task start date or length is changed, the other tasks that are dependent on it move accordingly

### Nice to Have's
+ [ ] Create the ability for tasks to have sub-tasks for cleaner organisation
+ [ ] Allow tasks to be displayed one after the other on the same line when they are linked
+ [ ] Colour code by owner
+ [ ] Edit task length within app

**Comment by iteles** [comment]
There are swathes and swathes of tools available, all doing variants of the same thing, some with a very focussed set of features, some that do a _lot_ of different things and even some that do a lot of different things _well_.

I found _many_ blog posts on the ‘best’ tools, even with very little overlap, like https://www.workzone.com/blog/gantt-chart-software/ and https://www.ntaskmanager.com/blog/best-gantt-chart-software/ (interestingly a lot of them were on the blogs of said apps).

I settled on 3 to try, mostly because they seemed more intuitive, didn’t require a huge amount of set and were aesthetically pleasing:
+ Monday.com
+ Aha.io (recommended via mentor on Startup School - see ‘Discarded’ section below
+ [TeamGantt](https://www.teamgantt.com/)

### 1. Monday.com

#### Reasons I chose to use it
+ _Very_ clean gantt chart, easy to follow
+ Pleasing aesthetic
+ Energetic tone of the website and setup instructions - it’s a very _friendly_ app

#### Reasons I stopped using it
+ No support for dependencies: https://support.monday.com/hc/en-us/articles/360001341429-Does-monday-com-have-dependencies-
![image](https://user-images.githubusercontent.com/4185328/49526953-c9e19b00-f8a8-11e8-9186-b6031d555616.png)
+ No ability to assign tasks to users who aren’t paid-for users
+ Timeline only available at $40 a month
+ Not possible to use offline

### 2. [TeamGantt](https://www.teamgantt.com/)

#### Reasons I chose to use it
+ Extremely clean-looking app
+ Very aesthetically pleasing
+ Free tier for up to 3 people
+ In-built time-tracking and _per task_ messaging

## Have not yet tried 

I’m only including the ones here that stuck out to me as worth trying for one reason or another; as I say, there are dozens of blog posts with many suggestions for others.

### [Todo.vu](https://todo.vu/)
This one looks by far to be the most promising and is probably the one I’d try next. Built for small businesses and freelancers and incorporating a large chunk of all business tasks that would be required rather than just one track, (**including CRM and time tracking**):
![image](https://user-images.githubusercontent.com/4185328/50727633-6a7be280-1115-11e9-9ef9-667facb2a5ea.png)

### [Teamwork](https://www.teamwork.com/project-management-software)
There is a _lot_ of functionality here - based around creating a task list. Thought it was interesting how  they also have a section on their site around comparing it to other popular task managers.
![image](https://user-images.githubusercontent.com/4185328/50727924-4242b280-111a-11e9-9c5c-a9844f6ab777.png)

### [Asana Timeline](https://asana.com/uses/timeline)
Asana being the behemoth in the ‘project management’ world that it is, it would be worth a quick look into how Timeline works.

### [Bitrix24](https://www.bitrix24.eu/tools/tasks_and_projects/)
This one pops up  a lot and appears to have quite the following. It doesn’t appeal to me because of the hard sell on the website and the feeling that it’s a little convoluted but might be worth a pomodoro of further investigation.


## Discarded
+ [Aha.io](https://www.aha.io/) - Does too much which means that even with section by section pop-up instructions , the learning curve is too great and I quickly lost interest.
+ [Tom’s planner](https://www.tomsplanner.com/) - I’ve used this in the past and found it a little too ‘excel-sheet-y’ and a little non-responsive
+ [Trello Gantt power-ups](https://asana.com/uses/timeline) - I’m not a big fan of trello and there was no native gantt functionality so I didn’t consider it a priority to review
+ Many were discarded for their 90s aesthetics, like [Rational Plan](https://www.rationalplan.com/) and [Hansoft](https://hansoft.com/))
